Reproduce surprising RunningMean overflow behavior
Test output:

Running main() from UnitTestsMain.cpp
Note: Google Test filter = *MathUtil*
[==========] Running 5 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 5 tests from MathUtil
[ RUN      ] MathUtil.IntLog2
[       OK ] MathUtil.IntLog2 (0 ms)
[ RUN      ] MathUtil.NextPowerOf2
[       OK ] MathUtil.NextPowerOf2 (0 ms)
[ RUN      ] MathUtil.SaturatingCast
[       OK ] MathUtil.SaturatingCast (0 ms)
[ RUN      ] MathUtil.RunningMeanUnsigned
d:\Source\UnitTests\Common\MathUtilTest.cpp(85): error: Expected equality of these values:
  mean.Mean()
    Which is: 6148914691236517220
  15
[  FAILED  ] MathUtil.RunningMeanUnsigned (0 ms)
[ RUN      ] MathUtil.RunningMeanSigned
d:\Source\UnitTests\Common\MathUtilTest.cpp(105): error: Expected equality of these values:
  mean.Mean()
    Which is: 6148914691236517220
  15
[  FAILED  ] MathUtil.RunningMeanSigned (0 ms)
[----------] 5 tests from MathUtil (1 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test suite ran. (2 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] MathUtil.RunningMeanUnsigned
[  FAILED  ] MathUtil.RunningMeanSigned

 2 FAILED TESTS